Repository sparc-request/sparc-fulfillment, pull requests merged in 2018-12, with the labels that each got.

#389 SJ - Double click fix
  app/assets/javascripts/tasks.js.coffee
  app/views/tasks/_form.html.haml
  app/views/tasks/create.js.coffee
  spec/features/tasks/create_task_spec.rb
  spec/features/tasks/view_task_spec.rb
Labels: 2.8.5, MUSC, enhancement

#390 KG - Force WaitHelpers to wait until jQuery loaded on page
  spec/support/features/wait_helpers.rb
Labels: 2.8.5, MUSC, bug, specs

#385 ML-replace_factory_girl_w_factory_bot
  Gemfile
  Gemfile.lock
  lib/tasks/fake_data.rake
  spec/factories/appointment.rb
  spec/factories/appointment_status.rb
  spec/factories/arm.rb
  spec/factories/clinical_provider.rb
  spec/factories/component.rb
  spec/factories/custom_appointment.rb
  spec/factories/document.rb
  spec/factories/fulfillment.rb
  spec/factories/human_subjects_info.rb
  spec/factories/identity.rb
  spec/factories/identity_counter.rb
  spec/factories/import.rb
  spec/factories/line_item.rb
  spec/factories/note.rb
  spec/factories/notification.rb
  spec/factories/organization.rb
  spec/factories/participant.rb
  spec/factories/pricing_map.rb
  spec/factories/pricing_setup.rb
  spec/factories/procedure.rb
  spec/factories/professional_organization.rb
  spec/factories/project_role.rb
  spec/factories/protocol.rb
  spec/factories/service.rb
  spec/factories/service_request.rb
  spec/factories/sparc_protocol.rb
  spec/factories/sub_service_request.rb
  spec/factories/subsidy.rb
  spec/factories/super_user.rb
  spec/factories/task.rb
  spec/factories/visit.rb
  spec/factories/visit_group.rb
  spec/spec_helper.rb
  spec/support/factory_girl.rb
Labels: 2.8.5

#392 ml-adding_notes_to_invoice_report
  app/controllers/reports_controller.rb
  app/views/reports/_invoice_report.html.haml
  config/locales/en.yml
  lib/reports/invoice_report.rb
Labels: 2.8.5, enhancement
