Repository sparc-request/sparc-fulfillment, pull requests merged in 2018-06, with the labels that each got.

#289 Adding RMID to reports [#154877352]
  app/models/protocol.rb
  dotenv.example
  lib/reports/auditing_report.rb
  lib/reports/project_summary_report.rb
  lib/reports/visit_report.rb
Labels: 2.8.0

#282 Jl - disabled procedures bug
  app/assets/javascripts/appointments.js.coffee
  spec/features/appointments/appointment_calendar/procedure_management/identity_completes_procedure_spec.rb
  spec/features/appointments/appointment_calendar/procedure_management/identity_messes_with_procedure_date_completed_spec.rb
Labels: 2.8.0, MUSC, bug

#287 JM - (SPARCFulfillment) Add Invoiced Flag and Lock Down Fulfillments that have been Invoiced
  app/assets/javascripts/appointments.js.coffee
  app/assets/stylesheets/application.sass
  app/views/appointments/_followup_calendar.html.haml
  app/views/appointments/_procedure.html.haml
  app/views/multiple_procedures/complete_all.js.coffee
  app/views/multiple_procedures/incomplete_all.js.coffee
  app/views/multiple_procedures/update_procedures.js.coffee
  config/locales/en.yml
Labels: 2.8.0

#288 wth - (SPARCFulfillment) Homepage Pagination
  app/views/protocols/_protocols.html.haml
Labels: 2.8.0, MUSC

#310 Klok import shows meaningful error message and destroys failed import…
  app/controllers/imports_controller.rb
  app/models/service.rb
Labels: 2.8.0
