Repository sparc-request/sparc-fulfillment, pull requests merged in 2018-08, with the labels that each got.

#326 KG - Make Invoice Report RMID Column Conditional
  lib/reports/invoice_report.rb
Labels: 2.8.0, MUSC, bug

#327 KG/AMC - Protocols List Sorting
  app/controllers/protocols_controller.rb
  app/models/protocol.rb
  app/views/protocols/_protocols.html.haml
  app/views/protocols/index.json.jbuilder
  config/database.yml.example
  lib/identity_organizations.rb
Labels: 2.8.0, MUSC, enhancement

#332 ml - form popup should persist with click
  app/views/appointments/new.js.coffee
  app/views/line_items/edit.js.coffee
  app/views/notes/index.js.coffee
  app/views/participants/new.js.coffee
  app/views/procedures/edit.js.coffee
  app/views/reports/new.js.coffee
  app/views/tasks/new.js.coffee
Labels: 2.8.5, bug

#333 added options to prevent modal close
  app/views/arms/new.js.coffee
  app/views/line_items/new.js.coffee
Labels: 2.8.0, bug
