Repository sparc-request/sparc-fulfillment, pull requests merged in 2019-05, with the labels that each got.

#445 KG - Show Individual Line Items for "Remove Service"
  app/assets/javascripts/study_schedule_management.js.coffee
  app/controllers/multiple_line_items_controller.rb
  app/helpers/study_level_activities_helper.rb
  app/models/line_item.rb
  app/views/multiple_line_items/destroy_line_items.js.coffee
  app/views/multiple_line_items/edit_line_items.js.coffee
  app/views/study_schedule/management/manage_services/_remove_line_items_form.html.haml
  spec/controllers/multiple_line_items_controller_spec.rb
  spec/features/study_schedule/management/identity_edits_services_spec.rb
Labels: 2.9.0, MUSC, enhancement

#446 JM- SLA Export bug
  app/views/documents/create.js.coffee
  app/views/notes/create.js.coffee
  spec/features/study_level_activities/identity_manages_documents_spec.rb
Labels: 2.9.0

#448 SJ - Updating bootstrap table cookie extension
  app/assets/javascripts/bootstrap-table-cookie.js
Labels: MUSC, bug

#450 JM - (SPARCFulfillment) SLA Export Bug
  app/helpers/study_level_activities_helper.rb
Labels: 2.9.0
