Repository sparc-request/sparc-fulfillment, pull requests merged in 2019-04, with the labels that each got.

#427 Ac adding delayed job monitoring
  .gitignore
  Capfile
  Gemfile
  Gemfile.lock
  config/schedule.rb
  dotenv.example
  lib/tasks/delayed_job_monitor.rake
Labels: 2.9.0, on hold

#441 SJ - Fixing historical arm data [#165355360]
  .travis.yml
  db/migrate/20181225173849_fix_historic_appointment_arm_data.rb
  db/schema.rb
Labels: 2.9.0, MUSC, bug

#444 SJ - Adding migration to fix deleted participant issues
  app/models/appointment.rb
  db/migrate/20181224134648_fix_deleted_participant_data.rb
Labels: 2.9.0, MUSC, bug

#439 JM - SLA Export
  app/assets/javascripts/application.js
  app/assets/javascripts/bootstrap-table-export.js
  app/assets/javascripts/bootstrap-table.js
  app/assets/javascripts/documents.js.coffee
  app/assets/javascripts/global.js.coffee
  app/assets/javascripts/protocols.js.coffee
  app/assets/javascripts/study_level_activities.js.coffee
  app/assets/javascripts/tableExport.js
  app/assets/javascripts/tasks.js.coffee
  app/assets/javascripts/xlsx.core.min.js
  app/helpers/study_level_activities_helper.rb
  app/models/component.rb
  app/views/line_items/_study_level_activity.json.jbuilder
  app/views/study_level_activities/_study_level_activities_table.html.haml
  config/locales/en.yml
Labels: 2.9.0

#440 SRY - Rake task to fix one time fee line items
  lib/tasks/fix_one_time_fee_line_items.rake
Labels: 2.9.0
