Repository sparc-request/sparc-fulfillment, pull requests merged in 2019-09, with the labels that each got.

#559 SJ - Updating travis build to Xenial
  .travis.yml
Labels: 3.0.0, MUSC

#537 JM - (SPARCFulfillment) Patient Registry search Bug
  app/controllers/participants_controller.rb
Labels: 3.0.0, MUSC

#540 JM - (SPARCFulfillment) Make Participant Name All Caps
  app/controllers/participants_controller.rb
  lib/tasks/fix_participant_names.rake
  spec/controllers/participants_controller_spec.rb
  spec/features/participants/patient_registry/identity_edits_participant_spec.rb
Labels: 3.0.0, MUSC

#541 JM - (SPARCFulfillment)- Participant Tracker -> Search Patient Registry Cookie holds
  app/views/participants/_associate_participants_to_protocol_modal.html.haml
Labels: 3.0.0, MUSC

#542 Jl- Protocols participant soft delete
  app/models/protocols_participant.rb
Labels: 3.0.0, MUSC

#558 SRY - Invoice report alphabetize and display inactive
  app/views/reports/new.js.coffee
  config/locales/en.yml
  db/schema.rb
  lib/invoice_report_grouped_options.rb
  spec/lib/invoice_report_grouped_options_spec.rb
Labels: MUSC

#554 Jl - Procedure pricing fix refactor
  lib/tasks/fix_procedures_service_costs.rake
Labels: 3.0.0, MUSC, refactors
