Repository sparc-request/sparc-fulfillment, pull requests merged in 2019-02, with the labels that each got.

#406 KG - Remove HR Number / Homepage Bug
  app/models/human_subjects_info.rb
Labels: 2.8.5, MUSC, bug, refactors

#407 ML - klok negative validation
  app/models/klok/entry.rb
Labels: 2.9.0, enhancement

#410 ML - changed tooltip wording
  app/helpers/protocol_helper.rb
  config/locales/en.yml
Labels: 2.9.0, MUSC, bug

#411 ML - invoice rpt sort pi by last name
  lib/reports/invoice_report.rb
Labels: 2.9.0, MUSC, enhancement

#412 SJ IE - Adding blue highlight when document is added
  app/assets/stylesheets/application.sass
  app/assets/stylesheets/notes.sass
  app/assets/stylesheets/study_level_activities.sass
  app/controllers/documents_controller.rb
  app/helpers/application_helper.rb
  app/helpers/study_level_activities_helper.rb
  app/models/document.rb
  app/views/documents/create.js.coffee
  app/views/notes/create.js.coffee
  spec/helpers/application_helper_spec.rb
Labels: 2.9.0, MUSC, enhancement

#399 SRY - Adding invoiced column to invoice report
  app/controllers/reports_controller.rb
  app/views/reports/_invoice_report.html.haml
  config/locales/en.yml
  lib/reports/invoice_report.rb
Labels: MUSC, enhancement
