Repository sparc-request/sparc-fulfillment, pull requests merged in 2020-06, with the labels that each got.

#731 Jl - Editing allowed for Account and Contact on non-clinical line items
  app/helpers/study_level_activities_helper.rb
  app/views/study_level_activities/_study_level_activity_form.html.haml
  config/locales/en.yml
Labels: 3.1.0, MUSC, cherry-pick

#740 SJ - Fixing Invoice Report
  lib/reports/invoice_report.rb
Labels: 3.1.0, MUSC, bug, cherry-pick

#742 Jl - Procedure percent subsidy bug
  app/models/appointment.rb
  spec/models/appointment_spec.rb
Labels: bug
