Repository sparc-request/sparc-fulfillment, pull requests merged in 2020-04, with the labels that each got.

#695 Jl - Remove editing functionality for non-clinical tab
  app/helpers/study_level_activities_helper.rb
  app/views/study_level_activities/_study_level_activities_table.html.haml
  spec/features/study_level_activities/identity_manages_line_items_spec.rb
Labels: 3.1.0, MUSC

#705 SJ - Fixing soft delete visit issue
  app/models/visit_group.rb
Labels: 3.1.0, MUSC, bug

#708 SRY - Add widget count to notes and documents
  app/assets/stylesheets/notifications.sass
  app/helpers/study_level_activities_helper.rb
Labels: MUSC

#709 Jl - Remove editing nonclinical tab
  app/views/study_level_activities/_study_level_activities_table.html.haml
  config/locales/en.yml
Labels: 3.1.0, MUSC
