Repository sparc-request/sparc-fulfillment, pull requests merged in 2020-05, with the labels that each got.

#711 (JM) SAW - Participant Tracker Table No Horizontal Scroll
  app/assets/stylesheets/participants.sass
Labels: MUSC

#717 SJ - Reworking Document Logic
  app/controllers/documents_controller.rb
  app/views/documents/create.js.coffee
  app/views/documents/destroy.js.coffee
  spec/features/study_level_activities/identity_manages_documents_spec.rb
Labels: 3.1.0, MUSC, enhancement

#725 SJ - Components Move
  app/helpers/study_level_activities_helper.rb
  app/models/line_item.rb
  app/views/fulfillments/_fulfillment.json.jbuilder
  app/views/line_items/_study_level_activity.json.jbuilder
  app/views/study_level_activities/_fulfillment_form.html.haml
  app/views/study_level_activities/_study_level_activities_table.html.haml
  db/migrate/20200519191441_move_components_to_fulfillments.rb
  db/schema.rb
  spec/helpers/study_level_activities_helper_spec.rb
  spec/models/line_item_spec.rb
Labels: 3.1.0, MUSC, enhancement

#729 SJ - Participants HotFix
  app/controllers/participants_controller.rb
Labels: 3.1.0, MUSC, bug, cherry-pick
