Repository sparc-request/sparc-fulfillment, pull requests merged in 2020-09, with the labels that each got.

#778 Jl - Subsidy Report Approved Subsidy Total bug
  lib/reports/subsidy_report.rb
Labels: 3.2.0, MUSC, bug

#787 Jl - Subsidy Report Use Sparc Start and End Dates
  lib/reports/subsidy_report.rb
Labels: 3.2.0, MUSC, enhancement

#795 Jl - Subsidy Report Start and End Date Defaults
  lib/reports/subsidy_report.rb
Labels: 3.2.0, MUSC, enhancement

#792 KG - Update communication with SPARC API
  app/api/v1/base.rb
  dotenv.example
  lib/importers/sparc_fulfillment_importer.rb
  lib/remote_object_fetcher.rb
  lib/remote_request_builder.rb
  spec/api/v1/authentication_spec.rb
  spec/jobs/protocol_importer_job_spec.rb
  spec/jobs/service_importer_job_spec.rb
  spec/lib/remote_object_fetcher_spec.rb
  spec/lib/remote_request_builder_spec.rb
  spec/requests/api/user_updates_service_components_in_sparc_spec.rb
  spec/support/sparc_api.rb
  spec/support/webmock.rb
  vcr_cassettes/RemoteServiceUpdaterJob/_perform/should_make_a_request_to_the_SPARC_server.yml
  vcr_cassettes/reusable/sparc_api/get_project_role_1.yml
  vcr_cassettes/reusable/sparc_api/get_protocol_1.yml
  vcr_cassettes/reusable/sparc_api/get_service_1.yml
  vcr_cassettes/reusable/sparc_api/get_service_components_1.yml
  vcr_cassettes/reusable/sparc_api/get_service_level_component_1.yml
  vcr_cassettes/reusable/sparc_api/get_sub_service_request_1.yml
Labels: 3.2.0, enhancement

#798 Jl - Fulfillment Page Refactor
  app/helpers/study_level_activities_helper.rb
  app/views/line_items/_study_level_activity.json.jbuilder
  app/views/study_level_activities/_study_level_activities_table.html.haml
  config/locales/en.yml
  spec/features/study_level_activities/identity_manages_documents_spec.rb
  spec/features/study_level_activities/identity_manages_notes_spec.rb
Labels: 3.2.0, MUSC, enhancement
