Repository sparc-request/sparc-fulfillment, pull requests merged in 2022-01, with the labels that each got.

#914 SRY - Fixing notes identity label
  app/views/notes/_index.html.haml
  spec/factories/protocols_participant.rb
  spec/features/appointments/appointment_calendar/procedure_management/identity_creates_followup_note_spec.rb
  spec/features/appointments/appointment_calendar/procedure_management/identity_creates_procedure_note_spec.rb
  spec/features/appointments/appointment_calendar/procedure_management/identity_messes_with_procedure_date_completed_spec.rb
  spec/support/features/bootstrap_helpers.rb
Labels: MUSC, Version 3.3.0

#916 SJ - Patient Search
  app/controllers/participants_controller.rb
  app/helpers/participant_helper.rb
  app/views/participants/index.html.haml
  spec/features/participants/patient_registry/identity_views_patient_registry_spec.rb
Labels: bug, MUSC, cherry-pick, Version 3.3.0

#915 SJ - Fixing follow-up Appointment Logic
  app/models/appointment.rb
  app/views/tasks/create.js.coffee
Labels: bug, MUSC, cherry-pick, Version 3.3.0

#917 SRY - Fixing Visit Type for Custom Visits
  app/controllers/appointments_controller.rb
  app/views/appointments/_visit_type_dropdown.html.haml
  config/routes.rb
Labels: bug, MUSC, cherry-pick, Version 3.3.0

#919 SJ - Quantity Fulfilled
  app/models/line_item.rb
  app/views/line_items/_study_level_activity.json.jbuilder
Labels: bug, MUSC, cherry-pick, Version 3.3.0

#922 SJ - Appointment Validation
  app/views/appointments/_form.html.haml
  app/views/appointments/create.js.coffee
Labels: bug, MUSC, cherry-pick, Version 3.3.0

#923 SRY - Fixing appointment start and end date validation
  app/controllers/appointments_controller.rb
  app/models/appointment.rb
  app/views/appointments/_calendar.html.haml
  app/views/appointments/update.js.coffee
Labels: MUSC, cherry-pick, Version 3.3.0
